"""add phone number and change vote table name

Revision ID: 81beac61917f
Revises: 0808daa57e3d
Create Date: 2023-04-14 16:59:59.476169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81beac61917f'
down_revision = '0808daa57e3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users','phone_number')
    
    # ### end Alembic commands ###
